#:kivy 1.0

<MainScreen>
    AquaScreen:

        TopLayout:
            Title:
                text: 'AquaBeat'

        CenterLayout:

            AquaButton:
		        text: 'MASS STORAGE'
		        on_press: root.manager.current = 'storage'

	        AquaButton:
	    	    text: 'MEDIA PLAYER'
	    	    on_press: root.manager.current = 'mediaPlayer'

	        AquaButton:
	    	    text: 'BLUETOOTH MODE'

	    BottomLayout:
