#:kivy 1.0

<MediaPlayerScreen>
	AquaScreen:

		TopLayout:
		    BackButton:
		        on_press: root.manager.current = 'main'

		    Title:
			    text: 'Media Player'

			VolUpButton:

        CenterLayout:
            HorizontalSpace:

            Title:
                text: 'TODO list of tracks'

            VolDownLayout:

        BottomLayout:
            PrevButton:

            Title:
                # Empty, just a placeholder

            NextButton: